### ISSUE TITLE
Allow comments in flat files

### ISSUE THREAD

**Issue by rdooley** [rdooley/confidynt#9]
Allow inline comments for flat config files, not pushed to dynamo and therefore not be in a deployed env var file on a remote.

Suggestion for comment of the form

`MY_VAR="my_value"  ## my comment`

**EDIT**

See @verkestk comment below and implement separate-line comments

**Comment by verkestk** [comment]
A couple things that would be nice:

1. comment out optional config values but keep them around because they are useful
1. describe a parameter's purpose, dangers, etc.
1. describe valid values

If it's easier, I think separate-line comments would be more useful.

For example:

```
# Optional: Use NETWORK_INTERFACE_ID to attach to an elastic IP used for static IP routing.
# Be careful with this parameter. A mistake here could have your test environment taking
# over a production site.
# NETWORK_INTERFACE_ID="..."

...

# see https://github.com/.../.../blob/dev/core/daterange.py for valid formats
DATES_TO_INDEX="-2"
```

**Comment by rdooley** [comment]
I would say that's easier and very do able
